---
title: ""
author: ""
output: pdf_document
---

## Summary of paper:

Insert one paragraph summary in your own words

## Major concerns:

* Bulleted list of concerns
* Only concerns that are sufficiently important that they should prevent publication of the paper

## Minor concerns

* Bulleted list of concerns
* Even if the authors didn't fix these the papers would be ok, but they might improve the paper. 

## Typos and grammar

* These are any issues with typos and grammer you find that you would like to report. 

## Recommendation

Pick one of:

* Reject
* Major revisions
* Minor revisions
* Accept

Reject if you think that the methods, results, or claims are blatantly false. Reject if you think the paper has major flaws that could not be corrected. Reject if the paper is clearly not an improvement on the current state of the art. 

Pick major revisions if you think there are serious problems with the paper but that they can be corrected. If you ask for major revisions your default plan should be that if they can/do correct all of the major issues you pointed out, you would be prepared to accept the paper. 

*Do not ask for major revisions if you think the paper is uninteresting and you wouldn't accept it even if they did everything you said.*

Pick minor revisions if there are only minor issues with the paper that you are pretty sure the authors can correct and you would be prepared to accept if the authors address those issues.

Pick accept if there are only minor issues and those issues are only judgement calls on your part, as opposed to things that need to be fixed to justify the claims or to make methods/results/data clear. It is perfectly acceptable in this case to list the minor issues and to suggest acceptance.
